  version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 28017:27017
    environment:
      MONGODB_DATABASE: nest-tresastronautas
    volumes:
      - ./mongo:/data/db